config/routes.rb
BootstrapStarter::Application.routes.draw do

  # Disallow robots access if not production environment
  require 'robots_generator'
  match '/robots.txt' => RobotsGenerator

	#--------------------------------
	# all resources should be within the scope block below
	#--------------------------------
	scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do

		match '/admin', :to => 'admin#index', :as => :admin, :via => :get
		#devise_for :users, :path_names => {:sign_in => 'login', :sign_out => 'logout'}
		devise_for :users, :path_names => {:sign_in => 'login', :sign_out => 'logout'},
											 :controllers => {:omniauth_callbacks => "omniauth_callbacks"}

		namespace :admin do
      resources :pages
			resources :users
      resources :news
      resources :languages
      resources :categories
		end

		#get 'tinymce_assets' ,to: 'tinymceassets#index'
		post '/tinymce_assets', to: 'imageuploader#create', as: 'imageuploader'

		match "stories/check_permalink" => "stories#check_permalink", as: 'story_check_permalink', :via => :post
		match "stories/tag_search" => "stories#tag_search", as: 'story_tag_search', :via => :post, :defaults => { :format => 'json' }
		match "review/:id" => "stories#review", as: 'review'
		match "stories/:id/collaborator_search" => "stories#collaborator_search", as: 'story_collaborator_search', :via => :post, :defaults => { :format => 'json' }
		match "stories/:id/invite_collaborators" => "stories#invite_collaborators", as: 'story_invite_collaborators', :via => :post, :defaults => { :format => 'json' }
		match "stories/:id/remove_collaborator" => "stories#remove_collaborator", as: 'story_remove_collaborator', :via => :post, :defaults => { :format => 'json' }
		match "stories/:id/remove_invitation" => "stories#remove_invitation", as: 'story_remove_invitation', :via => :post, :defaults => { :format => 'json' }
		match "stories/index" => "stories#index", as: 'index', :via => :post, :defaults => { :format => 'json' }

		resources :stories do

			member do
        get 'preview'

        get 'collaborators'
        post 'collaborators'

        get 'get_data'

        put 'content', to: 'stories#save_content'
        post 'content', to: 'stories#new_content'

        delete 'tree', to: 'stories#destroy_tree_item'

        put 'media', to: 'stories#save_media'
        post 'media', to: 'stories#new_media'



        put 'section', to: 'stories#save_section'
        post 'section', to: 'stories#new_section'
        post 'up', to: 'stories#up'
        post 'down', to: 'stories#down'
        post 'up_slideshow', to: 'stories#up_slideshow'
        post 'down_slideshow', to: 'stories#down_slideshow'

        get 'sections'
        get 'publish', to: 'stories#publish'
        get 'clone', to: 'stories#clone'
        get 'export', to: 'stories#export'

        put 'slideshow', to: 'stories#save_slideshow'
        post 'slideshow', to: 'stories#new_slideshow'


        put 'embed_media', to: 'stories#save_embed_media'
        post 'embed_media', to: 'stories#new_embed_media'

			end

		end
		#match '/stories/:id/edit' => 'stories#get_story'

#		match "storyteller/:id" => "storyteller#index", as: 'storyteller_show'
#		match "storyteller/:id/staff_pick" => "storyteller#staff_pick", as: 'storyteller_staff_pick'
#		match "storyteller/:id/staff_unpick" => "storyteller#staff_unpick", as: 'storyteller_staff_unpick'


    # user settings section
		match "settings" => "settings#index", as: 'settings'
		match "settings/notifications" => "settings#notifications", as: 'settings_notifications'
		match "settings/remove_avatar" => "settings#remove_avatar", as: 'settings_remove_avatar'
		match "settings/check_nickname" => "settings#check_nickname", as: 'settings_check_nickname', :via => :post, :defaults => { :format => 'json' }
		match "settings/invitations" => "settings#invitations", as: 'settings_invitations', :via => :get
		match "settings/invitations/accept/:key" => "settings#accept_invitation", as: 'settings_accept_invitation', :via => :get
		match "settings/invitations/decline/:key" => "settings#decline_invitation", as: 'settings_decline_invitation', :via => :get
		match "settings/follow_user" => "settings#follow_user", as: 'settings_follow_user', :via => :post, :defaults => { :format => 'json' }
		match "settings/unfollow_user" => "settings#unfollow_user", as: 'settings_unfollow_user', :via => :post, :defaults => { :format => 'json' }

    # root pages
		match "demo" => "root#demo", as: 'demo'
    match "privacy" => "root#privacy", as: 'privacy'
		match "news" => "root#news", as: 'news'
		match "news/:id" => "root#news_show", as: 'news_show'
		match 'feedback' => 'root#feedback', :as => 'feedback', :via => [:get, :post]
		match 'todo_list' => 'root#todo_list', :as => 'todo_list'
		match "about" => "root#about", as: 'about'
		match "author/:user_id" => "root#author", as: 'author'
		match "embed/:story_id" => "root#embed", as: 'embed'
		match "feed" => "root#feed", as: 'feed', :format => 'atom'

    # published story url/actions
    match ":id" => "storyteller#index", as: 'storyteller_show'
		match ":id/staff_pick" => "storyteller#staff_pick", as: 'storyteller_staff_pick', :defaults => { :format => 'json' }
		match ":id/staff_unpick" => "storyteller#staff_unpick", as: 'storyteller_staff_unpick', :defaults => { :format => 'json' }
		match ":id/like" => "storyteller#like", as: 'storyteller_like', :defaults => { :format => 'json' }
		match ":id/unlike" => "storyteller#unlike", as: 'storyteller_unlike', :defaults => { :format => 'json' }
		match ":id/record_comment" => "storyteller#record_comment", as: 'storyteller_record_comment', :defaults => { :format => 'json' }

		root :to => 'root#index'
	  match "*path", :to => redirect("/#{I18n.default_locale}") # handles /en/fake/path/whatever

	end

	match '', :to => redirect("/#{I18n.default_locale}") # handles /
	match '*path', :to => redirect("/#{I18n.default_locale}/%{path}") # handles /not-a-locale/anything

end

app/views/admin/pages/_form.html.erb
<%= tinymce_assets %>
<%= tinymce %>

<%= semantic_form_for([:admin, @page]) do |f| %>
	<%= f.error_messages %>

	<%= f.inputs do %>
	  <%= f.input :name %>
	<% end %>

  <% create_sorted_translation_objects(@page.page_translations).each do |trans| %>
		<%= f.fields_for :page_translations, trans do |translation| %>

			<div id="form-<%= trans.locale %>" class="multilanguage_nested">
				<h3><%= t("app.language.#{trans.locale}") %></h3>

				<%= translation.input :title %>
				<%= translation.input :content, :as => :text, rows: 10, :input_html => { class: 'tinyEditor' } %>
				<%= translation.hidden_field :locale , :value => trans.locale %>
			</div>

		<% end %>
	<% end %>

  <div>
    <%= f.submit nil, :class => 'btn btn-primary' %>
	  <%= f.submit t('helpers.links.reset'), :class => 'btn btn-warning', :type => :reset, :name => :reset %>
	  <%= link_to t('helpers.links.cancel'), admin_pages_path, :class => 'btn btn-xs btn-warning' %>
  </div>
<% end %>

app/views/admin/pages/edit.html.erb
<%- model_class = Page -%>
<% title t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "Edit #{model_class.model_name.human}") %>
<div>
	<%= link_to t('helpers.links.list'), admin_pages_path,
  :class => 'btn btn-default' %>
	<%= link_to t('helpers.links.admin'), admin_path,
  :class => 'btn btn-default' %>
</div>

<%= render :partial => 'form' %>

app/views/admin/pages/index.html.erb
<%- model_class = Page -%>
<%- model_class_trans = PageTranslation -%>
<% title t '.title', :default => model_class.model_name.human.pluralize %>

<div>
  <%= link_to t('.new', :default => t("helpers.links.new")),
              new_admin_page_path,
              :class => 'btn btn-primary' %>
  <%= link_to t('helpers.links.admin'), admin_path,
  :class => 'btn btn-default' %>
</div>

<table class="table table-striped display">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class_trans.human_attribute_name(:title) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= link_to page.name, admin_page_path(page) %></td>
        <td><%= page.title %></td>
        <td>
          <%= link_to t('app.buttons.edit'),
                      edit_admin_page_path(page), :class => 'btn btn-xs btn-default' %>
          <%= link_to t('app.buttons.delete'),
                      admin_page_path(page),
                      :method => :delete,
                      :data => { :confirm => I18n.t("helpers.links.confirm") },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/pages/new.html.erb
<%- model_class = Page -%>
<% title t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %>
<div>
	<%= link_to t('helpers.links.list'), admin_pages_path,
  :class => 'btn btn-default' %>
	<%= link_to t('helpers.links.admin'), admin_path,
  :class => 'btn btn-default' %>
</div>

<%= render :partial => 'form' %>

app/views/admin/pages/show.html.erb
<%- model_class = Page -%>
<%- model_class_trans = PageTranslation -%>
<% title t '.title', :default => model_class.model_name.human %>


<div>
  <%= link_to t('.back', :default => t("helpers.links.back")),
              admin_pages_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_admin_page_path(@page), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              admin_page_path(@page),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm")) },
              :class => 'btn btn-danger' %>
	<%= link_to t('helpers.links.admin'), admin_path, :class => 'btn btn-default' %>
</div>

<p><strong><%= model_class.human_attribute_name(:name) %>:</strong>
<%= @page.name %></p>

<p><strong><%= model_class_trans.human_attribute_name(:title) %>:</strong>
<%= @page.title %></p>

<p><strong><%= model_class.human_attribute_name(:content) %>:</strong></p>
<div class="todo tinymce_format">
  <%= simple_format_no_tags(@page.content, {}, {sanitize: false}) %>
</div>