config/routes.rb
BootstrapStarter::Application.routes.draw do

  # Disallow robots access if not production environment
  require 'robots_generator'
  match '/robots.txt' => RobotsGenerator

	#--------------------------------
	# all resources should be within the scope block below
	#--------------------------------
	scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do

		match '/admin', :to => 'admin#index', :as => :admin, :via => :get
		#devise_for :users, :path_names => {:sign_in => 'login', :sign_out => 'logout'}
		devise_for :users, :path_names => {:sign_in => 'login', :sign_out => 'logout'},
											 :controllers => {:omniauth_callbacks => "omniauth_callbacks"}

		namespace :admin do
      resources :pages
			resources :users
      resources :news
      resources :languages
      resources :categories
		end

		#get 'tinymce_assets' ,to: 'tinymceassets#index'
		post '/tinymce_assets', to: 'imageuploader#create', as: 'imageuploader'

		match "stories/check_permalink" => "stories#check_permalink", as: 'story_check_permalink', :via => :post
		match "stories/tag_search" => "stories#tag_search", as: 'story_tag_search', :via => :post, :defaults => { :format => 'json' }
		match "review/:id" => "stories#review", as: 'review'
		match "stories/:id/collaborator_search" => "stories#collaborator_search", as: 'story_collaborator_search', :via => :post, :defaults => { :format => 'json' }
		match "stories/:id/invite_collaborators" => "stories#invite_collaborators", as: 'story_invite_collaborators', :via => :post, :defaults => { :format => 'json' }
		match "stories/:id/remove_collaborator" => "stories#remove_collaborator", as: 'story_remove_collaborator', :via => :post, :defaults => { :format => 'json' }
		match "stories/:id/remove_invitation" => "stories#remove_invitation", as: 'story_remove_invitation', :via => :post, :defaults => { :format => 'json' }
		match "stories/index" => "stories#index", as: 'index', :via => :post, :defaults => { :format => 'json' }

		resources :stories do

			member do
        get 'preview'

        get 'collaborators'
        post 'collaborators'

        get 'get_data'

        put 'content', to: 'stories#save_content'
        post 'content', to: 'stories#new_content'

        delete 'tree', to: 'stories#destroy_tree_item'

        put 'media', to: 'stories#save_media'
        post 'media', to: 'stories#new_media'



        put 'section', to: 'stories#save_section'
        post 'section', to: 'stories#new_section'
        post 'up', to: 'stories#up'
        post 'down', to: 'stories#down'
        post 'up_slideshow', to: 'stories#up_slideshow'
        post 'down_slideshow', to: 'stories#down_slideshow'

        get 'sections'
        get 'publish', to: 'stories#publish'
        get 'clone', to: 'stories#clone'
        get 'export', to: 'stories#export'

        put 'slideshow', to: 'stories#save_slideshow'
        post 'slideshow', to: 'stories#new_slideshow'


        put 'embed_media', to: 'stories#save_embed_media'
        post 'embed_media', to: 'stories#new_embed_media'

			end

		end
		#match '/stories/:id/edit' => 'stories#get_story'

#		match "storyteller/:id" => "storyteller#index", as: 'storyteller_show'
#		match "storyteller/:id/staff_pick" => "storyteller#staff_pick", as: 'storyteller_staff_pick'
#		match "storyteller/:id/staff_unpick" => "storyteller#staff_unpick", as: 'storyteller_staff_unpick'


    # user settings section
		match "settings" => "settings#index", as: 'settings'
		match "settings/notifications" => "settings#notifications", as: 'settings_notifications'
		match "settings/remove_avatar" => "settings#remove_avatar", as: 'settings_remove_avatar'
		match "settings/check_nickname" => "settings#check_nickname", as: 'settings_check_nickname', :via => :post, :defaults => { :format => 'json' }
		match "settings/invitations" => "settings#invitations", as: 'settings_invitations', :via => :get
		match "settings/invitations/accept/:key" => "settings#accept_invitation", as: 'settings_accept_invitation', :via => :get
		match "settings/invitations/decline/:key" => "settings#decline_invitation", as: 'settings_decline_invitation', :via => :get
		match "settings/follow_user" => "settings#follow_user", as: 'settings_follow_user', :via => :post, :defaults => { :format => 'json' }
		match "settings/unfollow_user" => "settings#unfollow_user", as: 'settings_unfollow_user', :via => :post, :defaults => { :format => 'json' }

    # root pages
		match "demo" => "root#demo", as: 'demo'
    match "privacy" => "root#privacy", as: 'privacy'
		match "news" => "root#news", as: 'news'
		match "news/:id" => "root#news_show", as: 'news_show'
		match 'feedback' => 'root#feedback', :as => 'feedback', :via => [:get, :post]
		match 'todo_list' => 'root#todo_list', :as => 'todo_list'
		match "about" => "root#about", as: 'about'
		match "author/:user_id" => "root#author", as: 'author'
		match "embed/:story_id" => "root#embed", as: 'embed'
		match "feed" => "root#feed", as: 'feed', :format => 'atom'

    # published story url/actions
    match ":id" => "storyteller#index", as: 'storyteller_show'
		match ":id/staff_pick" => "storyteller#staff_pick", as: 'storyteller_staff_pick', :defaults => { :format => 'json' }
		match ":id/staff_unpick" => "storyteller#staff_unpick", as: 'storyteller_staff_unpick', :defaults => { :format => 'json' }
		match ":id/like" => "storyteller#like", as: 'storyteller_like', :defaults => { :format => 'json' }
		match ":id/unlike" => "storyteller#unlike", as: 'storyteller_unlike', :defaults => { :format => 'json' }
		match ":id/record_comment" => "storyteller#record_comment", as: 'storyteller_record_comment', :defaults => { :format => 'json' }

		root :to => 'root#index'
	  match "*path", :to => redirect("/#{I18n.default_locale}") # handles /en/fake/path/whatever

	end

	match '', :to => redirect("/#{I18n.default_locale}") # handles /
	match '*path', :to => redirect("/#{I18n.default_locale}/%{path}") # handles /not-a-locale/anything

end

app/views/shared/_carousel.html.erb
<% has_highlight = @highlight.present? %>
<% content_for(:header) { %>
<header>
  <% if @stories_for_slider.present? %>
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
      <% if has_highlight %>
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
      <% end %>
       <% @stories_for_slider.each_with_index { |t,i| %>
          <% slide_index = has_highlight ? i + 1 : i %>
          <li data-target="#carousel-example-generic" data-slide-to="<%= slide_index %>" class='<%= slide_index == 0 ? " active" : "" %>'></li>
        <% } %>
      </ol>
      <!-- Wrapper for slides -->
      <div class="carousel-inner" role="listbox">
        <% if has_highlight %>
          <div class="item active" data-is-highlight>
            <% tmp = "<div class='img' style='background: url(/assets/png/thumbnail_mask.png) 100% 100% , url(#{@highlight.image.file.url(:slider)}) center center no-repeat; background-size:cover;'></div>".html_safe %>
            <%= @highlight.url.present? ? (link_to(@highlight.url, target: '_blank') do tmp end) : tmp %>
            <div class="carousel-caption" lang="<%= I18n.locale %>">
              <% tmp = "<div class='title'>#{@highlight.caption}</div>".html_safe %>
              <%= @highlight.url.present? ? (link_to(@highlight.url, target: '_blank') do tmp end) : tmp %>
            </div>
          </div>
        <% end %>
        <% @stories_for_slider.each_with_index { |story,i| %>
          <% slide_index = has_highlight ? i + 1 : i %>
          <% story.use_app_locale_if_translation_exists %>
          <div class='item<%= slide_index == 0 ? " active" : "" %>'>
            <%= link_to storyteller_show_path(story.permalink) do %>
              <div class='img' style="background: url(/assets/png/thumbnail_mask.png) 100% 100% , url(<%= story.show_asset.file.url(:slider) %>) center center no-repeat; background-size:cover;"></div>
            <% end %>
            <div class="carousel-caption" lang="<%= story.current_locale %>">
              <%= link_to  storyteller_show_path(story.permalink) do %>
                <div class='title'><%= story.title %></div>
                <% if false #story.about.present? %>
                <div class='descr'><%= strip_tags_nbsp(story.about).html_safe if story.about.present? %></div>
                <% end %>
              <% end %>
              <div class='storytype'>
                <div class='storytype-logo story_type_<%= story.story_type_id %>' title='<%= get_story_type_name(story.story_type_id) %>'></div>
                <div class='storytype-label' lang='<%= I18n.locale %>'><%= get_story_type_name(story.story_type_id) %></div>
              </div>
            </div>
          </div>
        <% } %>
      </div>
      <!-- Controls -->
      <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="icon arrow-left" aria-hidden="true"></span>
        <span class="sr-only"><%= t('helpers.links.previous') %></span>
      </a>
      <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="icon arrow-right" aria-hidden="true"></span>
        <span class="sr-only"><%= t('helpers.links.next') %></span>
      </a>
      <!-- Sticker -->
      <div class='sticker' style="display: none;">
        <div class='sticker-container'>
          <%
            locale_line_width = {
              title: { en: 30, ka: 26, ru: 30, az: 30, hy: 30 },
              descr: { en: 40, ka: 30, ru: 40, az: 30, hy: 30 }
            }
            line_width_title = locale_line_width[:title][I18n.locale]
            line_width_descr = locale_line_width[:descr][I18n.locale]
            theme_title = word_wrap(@theme.name.split.map(&:capitalize).join(' '), line_width: line_width_title).gsub("\n", "<br/>").html_safe
            theme_descr = word_wrap(@theme.description, line_width: line_width_descr).gsub("\n", "<br/>").html_safe
            theme_date = word_wrap(@theme.edition, line_width: line_width_descr).gsub("\n", "<br/>").html_safe
          %>
          <%= link_to theme_path(@theme.permalink), class: "sticker-placeholder" do %>
            <div class='title'><%= theme_title %></div><div class='descr'><%= theme_descr %></div><div class='sep'></div><div class='date'><%= theme_date %></div>
          <% end %>
          <%= link_to theme_path(@theme.permalink), class: "sticker-text" do %>
            <div class='title'><%= theme_title %></div><div class='descr'><%= theme_descr %></div><div class='sep'></div><div class='date'><%= theme_date %></div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</header>
<% } %>

app/views/shared/_filter.html.erb
<div id="filter">

  <ul class="nav s navbar-left">
    <li><div class='all-stories'><%= t('filters.all_stories') %></div></li>
    <li class="li-sort-label"><span class="sort-label"><%= t('filters.sort_header') %></span></li>
    <li class="dropdown dropdown-hover sort afilter">
      <a href="#" class="dropdown-toggle<%= @story_filter_sort_recent ? '' : ' selected' %>"
          data-toggle="dropdown" tabindex="17"  title="<%= t('filters.sort_title') %>"
          data-filtered-by="<%= @story_filter_sort_permalink %>" data-filter-type="sort"
          data-filter-default="recent">
        <span><%= @story_filter_sort %></span><i class='caret'></i></a>
      <ul class="dropdown-menu afilter-list">
        <% I18n.t('filters.sort').each do |key, value| %>
          <li class="dropdown">
            <%= link_to value, url_for(params.merge(:sort => key)), :class => @story_filter_sort == value ? 'active' : '', :"data-filter" => key %>
          </li>
        <% end %>
      </ul>
    </li>
    <li class="dropdown dropdown-hover afilter">
      <a href="#" class="dropdown-toggle<%= @story_filter_type_all ? '' : ' selected' %>"
        data-toggle="dropdown" tabindex="18"  title="<%= t('filters.sort_title') %>"
        data-filtered-by="<%= @story_filter_type_permalink %>" data-filter-type="type"
        data-filter-default="all"><%= t('helpers.links.story_types') %><i class="caret"></i></a>
        <ul class="dropdown-menu afilter-list">
           <li class="dropdown">
          <%= link_to I18n.t('filters.all'), "#", :class => @story_filter_type == I18n.t('filters.all') ? 'active' : '', :"data-filter" => 'all' %>
        </li>
          <% @story_types.each do |item| %>
            <li class="dropdown">
              <%= link_to item.name, "#", :class => @story_filter_type == item.name ? 'active' : '', :"data-filter" => item.permalink %>
            </li>
          <% end %>
        </ul>
    </li>

    <% if @story_filter_show_following %>
      <li class="afilter">
        <%= link_to url_for(params.merge(:following => !@story_filter_following)),
          :title => @story_filter_following ? t('filters.following_title_active') : t('filters.following_title'),
          :class => "following #{@story_filter_following == true ? 'active' : ''}",
          :tabindex => 19, :"data-filtered-by" => @story_filter_following ,
          :"data-filter-type"=>'following',
          :'data-title' => t('filters.following_title'), :'data-title-active' => t('filters.following_title_active') do %>

           <i class='s i-follow-b <%= "#{@story_filter_following == true ? 'v' : 'h'}"%>'></i><%=  "#{t('filters.following')}" %>
         <% end %>
      </li>
    <% end %>
   <% if @editable == true %>
      <% if @themes_published.present? %>
        <li class="dropdown dropdown-hover theme afilter">
          <a href="#" class="dropdown-toggle<%= @story_filter_theme_all ? '' : ' selected' %>"
            data-toggle="dropdown" tabindex="15" title="<%= t('filters.theme_title') %>"
            data-filtered-by="<%= @story_filter_theme_permalink %>"
            data-filter-type="theme" data-filter-default-label="<%= t('filters.theme_header') %>"
            data-filter-default="all">
          <span><%= @story_filter_theme_all ? t('filters.theme_header') : @story_filter_theme %></span><i class='caret'></i></a>
          <ul class="dropdown-menu afilter-list">
            <li class="dropdown">
              <%= link_to I18n.t('filters.all'), "#", :class => @story_filter_theme == I18n.t('filters.all') ? 'active' : '', :"data-filter" => 'all' %>
            </li>
            <% @themes_published.each do |item| %>
              <li class="dropdown">
                <%= link_to item.name, "#", :class => @story_filter_theme == item.name ? 'active' : '', :"data-filter" => item.permalink %>
              </li>
            <% end %>
          </ul>
        </li>
      <% end %>

      <li class="afilter">
        <%= link_to url_for(params.merge(:not_published => !@story_filter_not_published)),
          :class => "not_published #{@story_filter_not_published == true ? 'active' : ''}",
            :tabindex => 13,
            :title => @story_filter_not_published ? t('filters.not_published_title_active') : t('filters.not_published_title'),
            :"data-filtered-by" => @story_filter_not_published , :"data-filter-type"=>'not_published',
            :'data-title' => t('filters.not_published_title'), :'data-title-active' => t('filters.not_published_title_active') do %>

         <i class='s i-not-published'></i><%=  "#{t('filters.not_published')}" %>
       <% end %>
      </li>


    <% end %>
  </ul>
</div>

app/views/shared/_filter_ajax.js.erb
$(".grid-wrapper").html("<%= escape_javascript(render({partial: 'shared/grid'})) %>");

app/views/shared/_grid.html.erb
<div class="grid-wrapper">
  <div class="grid col-4">
    <% if @stories.blank? %>
      <p>
        <%= t('.no_stories') %>
      </p>
    <% else %>
      <% @stories.each_with_index do |story,s_i| %>
        <% story.set_to_app_locale %>
        <div class="col n-3" lang="<%= story.current_locale %>">
          <%= render partial: "shared/grid_item" , locals:{:story=>story} %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= page_navigation_links @stories %>
</div>


<% if @editable %>
  <% content_for(:footer) { %>
    <script>var reviewer = "<%= escape_javascript(render :partial => 'shared/story_nav_modals') %>";</script>
  <% } %>
<% end %>

app/views/shared/_grid_item.html.erb
<%
  title = ""
  if story.about.present?
    title = truncate(strip_tags_nbsp(story.about), length: 160, separator: ' ')
  end

  path = @editable && !story.published ? preview_story_path(story, locale: story.current_locale) : storyteller_show_path(story.permalink, locale: story.current_locale)
%>

  <div class="story-thumbnail">
     <%= link_to path do %>
        <%= image_tag story.show_asset.file.url(:thumbnail) %>
        <div class="story-link">
          <div class='type story_type_<%= story.story_type_id %>' title='<%= get_story_type_name(story.story_type_id) %>'></div>
          <span title="<%= story.title %>"><%= story.title %></span>
       </div>
      <% end %>

    <% if @editable %>
      <div class="story-edit">
        <div class="story-edit-menu">
        <ul class="nav">
        <li class="dropdown dropdown-hover">
         <button type="button"  class="btn dropdown-toggle" data-toggle="dropdown">
          <i class="glyphicon glyphicon-pencil" ></i>
        </button>
          <ul class="dropdown-menu">
            <% user_role = story.user_role(current_user.id) %>
            <% if user_role.present? && user_role.role == Story::ROLE[:translator] %>
              <li>
                <%= link_to  sections_story_path(story,tr:true,tr_from:story.story_locale,tr_to:user_role.translation_locales_array.first), title: t('helpers.links.story_menu.title.translations') do %>
                  <i class="glyphicon glyphicon-globe"></i><%=t('helpers.links.story_menu.link.translations')%>
                <% end %>
              </li>
            <% else %>
              <li>
                <%= link_to  sections_story_path(story), title: t('helpers.links.story_menu.title.story') do %>
                <i class="glyphicon glyphicon-picture"></i><%=t('helpers.links.story_menu.link.story')%>
                <% end %>
              </li>
              <li>
                <%= link_to  collaborators_story_path(story), title: t('helpers.links.story_menu.title.collaborators') do %>
                <i class="glyphicon glyphicon-user"></i><%=t('helpers.links.story_menu.link.collaborators')%>
                <% end %>
              </li>
              <li>
                <%= link_to  sections_story_path(story,tr:true,tr_from:@tr_from,tr_to:@tr_to), title: t('helpers.links.story_menu.title.translations') do %>
                  <i class="glyphicon glyphicon-globe"></i><%=t('helpers.links.story_menu.link.translations')%>
                <% end %>
              </li>
              <li>
                <a href="#" id='btnPreview' class='preview' title="<%= t('helpers.links.story_menu.title.preview') %>" data-link='<%= path %>'
                    data-modalos-id='modalos-preview' data-type='story'>
                  <i class="glyphicon glyphicon-eye-open" ></i><%= t('helpers.links.story_menu.link.preview') %>
                </a>
              </li>
              <% if !story.published %>
                <li>
                   <a href="#" id='btnReviewer' title="<%= t('helpers.links.story_menu.title.review') %>" data-modalos-id='modalos-reviewer'
                      data-reviewer-key='<%= review_url(story.reviewer_key) %>'
                      data-title='<%= story.title %>'>
                    <i class="glyphicon glyphicon-share" ></i><%= t('helpers.links.story_menu.link.review') %>
                  </a>
                </li>
              <% end %>
              <li>
                <%
                  title = story.published ? t('helpers.links.story_menu.title.unpublish') : t('helpers.links.story_menu.title.publish')
                  link_text = story.published ? t('helpers.links.story_menu.link.unpublish') : t('helpers.links.story_menu.link.publish')
                %>
                <a href="#" id='btnPublish' title='<%= title %>'
                    <%= 'class="disabled"' if !story.published %> data-link='<%= publish_story_path(story) %>'>
                  <i class="glyphicon glyphicon-globe" ></i><span><%= link_text %></span>
                </a>
              </li>
              <li>
                <%= link_to clone_story_path(story) ,  title: t('helpers.links.story_menu.title.clone') do %>
                  <i class="glyphicon glyphicon-camera"></i><%=t('helpers.links.story_menu.link.clone')%>
                <% end %>
              </li>
              <li>
                <%= link_to export_story_path(story) ,  title: t('helpers.links.story_menu.title.export') do %>
                  <i class="glyphicon glyphicon-download"></i><%=t('helpers.links.story_menu.link.export')%>
                <% end %>
              </li>
              <li>
                <%= link_to story, title: t('helpers.links.story_menu.title.delete_story'), confirm: t("helpers.links.confirm"), method: :delete do %>
                  <i class="glyphicon glyphicon-remove"></i><%=t('helpers.links.story_menu.link.delete_story')%>
                <% end %>
              </li>
            <% end %>
          </ul>
          </li>
          </ul>
        </div>
      </div>
      <div class='story-message'></div>
    <% end %>

  </div>
  <div class='story-info'>
    <div class="story-caption">
      <% truncate_length = story.current_locale == 'ka' ? 130 : 150 %>
      <%
        about = strip_tags_nbsp(story.about) if story.about.present?
        if about.present?
      %>
          <%= link_to truncate(about, length: truncate_length, separator: ' ').html_safe,
              path, :title => about.html_safe, :lang => story.current_locale %>
      <% end %>
    </div>
    <div class="story-misc">
      <div class="views" title="<%= t('app.common.views') %>"><%= t('app.common.views') %>: <%= story.impressions_count %></div>
      <div class="sep"></div>
      <div class="publish-date" title="<%= t('app.common.publish_date') %>">
        <%= l(story.published_at,:format => :publish) if story.published_at.present? %>
      </div>
    </div>
  </div>

app/views/shared/_settings_nav.html.erb
<ul id="settings-navigation" class="nav nav-tabs">
  <% cls = current_page?(settings_path) ? 'class=active' : '' %>
  <li <%=cls %>>
    <%= link_to settings_path, :title => t('settings.index.title') do %>
      <span class="glyphicon glyphicon-cog"></span>
      <span class="nav-text">
        <%= t('settings.index.title') %>
      </span>
    <% end %>
  </li>
  <% cls = current_page?(settings_notifications_path) ? 'class=active' : '' %>
  <li <%=cls %>>
    <%= link_to settings_notifications_path, :title => t('settings.notifications.title') do %>
      <span class="glyphicon glyphicon-envelope"></span>
      <span class="nav-text">
        <%= t('settings.notifications.title') %>
      </span>
    <% end %>
  </li>
  <% if current_user.role? User::ROLES[:coordinator] %>
    <% cls = current_page?(settings_invitations_path) ? 'class=active' : '' %>
    <li <%=cls %>>
      <%= link_to settings_invitations_path, :title => t('settings.invitations.title') do %>
        <span class="glyphicon glyphicon-user"></span>
        <span class="nav-text">
          <%= t('settings.invitations.title') %>
        </span>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/shared/_story_nav.html.erb
<% if @edit_story_role != Story::ROLE[:translator] %>
  <ul id="story-navigation" class="nav nav-tabs">
    <% cls = !@tr && current_page?(sections_story_path(@story)) ? 'class=active' : '' %>
    <li <%=cls %>>
      <%= link_to sections_story_path(@story), title: t('helpers.links.story_menu.title.story') do %>
        <span class="glyphicon glyphicon-picture"></span>
        <span class="nav-text">
          <%=t('helpers.links.story_menu.link.story')%>
        </span>
      <% end %>
    </li>
    <% cls = current_page?(collaborators_story_path(@story)) ? 'class=active' : '' %>
    <li <%=cls %>>
      <%= link_to collaborators_story_path(@story), title: t('helpers.links.story_menu.title.collaborators') do %>
        <span class="glyphicon glyphicon-user"></span>
        <span class="nav-text">
          <%=t('helpers.links.story_menu.link.collaborators')%>
        </span>
      <% end %>
    </li>
    <% cls = @tr && current_page?(sections_story_path(@story)) ? 'class=active' : '' %>
    <li <%=cls %>>
      <%= link_to sections_story_path(@story,tr:true,from:@tr_from,to:@tr_to), title: t('helpers.links.story_menu.title.translations') do %> 
        <span class="glyphicon glyphicon-globe"></span>
        <span class="nav-text">
          <%= t('helpers.links.story_menu.link.translations') %>
        </span>
      <% end %>
    </li>
    <li>
      <%= link_to clone_story_path(@story), title: t('helpers.links.story_menu.title.clone') do %>
        <span class="glyphicon glyphicon-camera"></span>
        <span class="nav-text">
          <%=t('helpers.links.story_menu.link.clone')%>
        </span>
      <% end %> 
    </li>                        
    <li>  
      <%= link_to export_story_path(@story), title: t('helpers.links.story_menu.title.export') do %>
        <span class="glyphicon glyphicon-download"></span>
        <span class="nav-text">
          <%=t('helpers.links.story_menu.link.export')%>
        </span>
      <% end %>
    </li>                          
  </ul>
<% end %>

app/views/shared/_story_nav_modals.html.erb
<div id="modalos-reviewer" style="width:100%;height:100%;" >
  <div class="page-header">
    <div class="block">
      <h1>
        <%= t('stories.reviewer_key.title') %>
      </h1>
    </div>
  </div>
 <p id="review_instructions">
    <%= t('stories.reviewer_key.desc', :title => '[title]') %>
</p>
  
  <div><a id='review_url' href='[url]'>[url]</a></div>    
  <div>
    <button id="copy-button" class="btn btn-xs" data-clipboard-target="review_url"><%= t('.copy') %></button>
  </div>                          
  <div id="copied" style="display: none;" class="alert alert-success">
      <%= t('.copied') %>
  </div>     
</div>

app/views/shared/grid.js.erb
$(".grid-wrapper").html("<%= escape_javascript(render({partial: 'shared/grid'})) %>");