config/routes.rb
BootstrapStarter::Application.routes.draw do

  # Disallow robots access if not production environment
  require 'robots_generator'
  match '/robots.txt' => RobotsGenerator

	#--------------------------------
	# all resources should be within the scope block below
	#--------------------------------
	scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do

		match '/admin', :to => 'admin#index', :as => :admin, :via => :get
		#devise_for :users, :path_names => {:sign_in => 'login', :sign_out => 'logout'}
		devise_for :users, :path_names => {:sign_in => 'login', :sign_out => 'logout'},
											 :controllers => {:omniauth_callbacks => "omniauth_callbacks"}

		namespace :admin do
      resources :pages
			resources :users
      resources :news
      resources :languages
      resources :categories
		end

		#get 'tinymce_assets' ,to: 'tinymceassets#index'
		post '/tinymce_assets', to: 'imageuploader#create', as: 'imageuploader'

		match "stories/check_permalink" => "stories#check_permalink", as: 'story_check_permalink', :via => :post
		match "stories/tag_search" => "stories#tag_search", as: 'story_tag_search', :via => :post, :defaults => { :format => 'json' }
		match "review/:id" => "stories#review", as: 'review'
		match "stories/:id/collaborator_search" => "stories#collaborator_search", as: 'story_collaborator_search', :via => :post, :defaults => { :format => 'json' }
		match "stories/:id/invite_collaborators" => "stories#invite_collaborators", as: 'story_invite_collaborators', :via => :post, :defaults => { :format => 'json' }
		match "stories/:id/remove_collaborator" => "stories#remove_collaborator", as: 'story_remove_collaborator', :via => :post, :defaults => { :format => 'json' }
		match "stories/:id/remove_invitation" => "stories#remove_invitation", as: 'story_remove_invitation', :via => :post, :defaults => { :format => 'json' }
		match "stories/index" => "stories#index", as: 'index', :via => :post, :defaults => { :format => 'json' }

		resources :stories do

			member do
        get 'preview'

        get 'collaborators'
        post 'collaborators'

        get 'get_data'

        put 'content', to: 'stories#save_content'
        post 'content', to: 'stories#new_content'

        delete 'tree', to: 'stories#destroy_tree_item'

        put 'media', to: 'stories#save_media'
        post 'media', to: 'stories#new_media'



        put 'section', to: 'stories#save_section'
        post 'section', to: 'stories#new_section'
        post 'up', to: 'stories#up'
        post 'down', to: 'stories#down'
        post 'up_slideshow', to: 'stories#up_slideshow'
        post 'down_slideshow', to: 'stories#down_slideshow'

        get 'sections'
        get 'publish', to: 'stories#publish'
        get 'clone', to: 'stories#clone'
        get 'export', to: 'stories#export'

        put 'slideshow', to: 'stories#save_slideshow'
        post 'slideshow', to: 'stories#new_slideshow'


        put 'embed_media', to: 'stories#save_embed_media'
        post 'embed_media', to: 'stories#new_embed_media'

			end

		end
		#match '/stories/:id/edit' => 'stories#get_story'

#		match "storyteller/:id" => "storyteller#index", as: 'storyteller_show'
#		match "storyteller/:id/staff_pick" => "storyteller#staff_pick", as: 'storyteller_staff_pick'
#		match "storyteller/:id/staff_unpick" => "storyteller#staff_unpick", as: 'storyteller_staff_unpick'


    # user settings section
		match "settings" => "settings#index", as: 'settings'
		match "settings/notifications" => "settings#notifications", as: 'settings_notifications'
		match "settings/remove_avatar" => "settings#remove_avatar", as: 'settings_remove_avatar'
		match "settings/check_nickname" => "settings#check_nickname", as: 'settings_check_nickname', :via => :post, :defaults => { :format => 'json' }
		match "settings/invitations" => "settings#invitations", as: 'settings_invitations', :via => :get
		match "settings/invitations/accept/:key" => "settings#accept_invitation", as: 'settings_accept_invitation', :via => :get
		match "settings/invitations/decline/:key" => "settings#decline_invitation", as: 'settings_decline_invitation', :via => :get
		match "settings/follow_user" => "settings#follow_user", as: 'settings_follow_user', :via => :post, :defaults => { :format => 'json' }
		match "settings/unfollow_user" => "settings#unfollow_user", as: 'settings_unfollow_user', :via => :post, :defaults => { :format => 'json' }

    # root pages
		match "demo" => "root#demo", as: 'demo'
    match "privacy" => "root#privacy", as: 'privacy'
		match "news" => "root#news", as: 'news'
		match "news/:id" => "root#news_show", as: 'news_show'
		match 'feedback' => 'root#feedback', :as => 'feedback', :via => [:get, :post]
		match 'todo_list' => 'root#todo_list', :as => 'todo_list'
		match "about" => "root#about", as: 'about'
		match "author/:user_id" => "root#author", as: 'author'
		match "embed/:story_id" => "root#embed", as: 'embed'
		match "feed" => "root#feed", as: 'feed', :format => 'atom'

    # published story url/actions
    match ":id" => "storyteller#index", as: 'storyteller_show'
		match ":id/staff_pick" => "storyteller#staff_pick", as: 'storyteller_staff_pick', :defaults => { :format => 'json' }
		match ":id/staff_unpick" => "storyteller#staff_unpick", as: 'storyteller_staff_unpick', :defaults => { :format => 'json' }
		match ":id/like" => "storyteller#like", as: 'storyteller_like', :defaults => { :format => 'json' }
		match ":id/unlike" => "storyteller#unlike", as: 'storyteller_unlike', :defaults => { :format => 'json' }
		match ":id/record_comment" => "storyteller#record_comment", as: 'storyteller_record_comment', :defaults => { :format => 'json' }

		root :to => 'root#index'
	  match "*path", :to => redirect("/#{I18n.default_locale}") # handles /en/fake/path/whatever

	end

	match '', :to => redirect("/#{I18n.default_locale}") # handles /
	match '*path', :to => redirect("/#{I18n.default_locale}/%{path}") # handles /not-a-locale/anything

end

app/controllers/storyteller_controller.rb
class StorytellerController < ApplicationController
	layout false
  skip_before_filter :verify_authenticity_token
  before_filter :authenticate_user!, :except => [:index, :record_comment]
  before_filter(:only => [:staff_pick, :staff_unpick]) do |controller_instance|
    controller_instance.send(:valid_role?, User::ROLES[:staff_pick])
  end


  def index
    sl = params[:sl]
    if sl.present? && I18n.locale.to_s != sl && I18n.available_locales.index(sl.to_sym)
      params.delete(:sl)
      redirect_to storyteller_show_path(params.merge({ locale: sl})), :notice => t('app.msgs.redirected_with_app_locale')
    else

      @story = Story.with_translations(I18n.locale).is_published.find_by_permalink(params[:id])

      if @story.present?
        @story.set_to_app_locale

# logger.debug "@@@@@@@@@@@@@@@@@@@@@@@@@"
# logger.debug "app locale = #{I18n.locale}; story locale = #{@story.current_locale}"

        impressionist(@story, :unique => [:session_hash]) # record the view count
        @story.reload
        @story.set_to_app_locale
        @stories = @story.next_stories # random_related_stories
        @story.set_to_app_locale

        @story.sections.includes([:media,:content,:embed_medium,:youtube,:slideshow])


# logger.debug "after reload app locale = #{I18n.locale}; story locale = #{@story.current_locale}"
# logger.debug "@@@@@@@@@@@@@@@@@@@@@@@@@"


        # record if the user has liked this story
        @user_likes = false
        @user_likes = current_user.voted_up_on? @story if user_signed_in?
        @is_following = Notification.already_following_user(current_user.id, @story.author_ids) if user_signed_in?

        @no_nav = true if params[:n] == 'n'

        @css.push("navbar.css", "navbar2.css", "storyteller.css", "modalos.css", "grid2.css")
        @js.push("storyteller.js","modalos.js","follow.js")

        respond_to do |format|
          format.html
        end

      else
        redirect_to root_path #, :notice => t('app.msgs.does_not_exist')
      end
    end
  end


  def staff_pick
  	story = Story.is_published.find_by_permalink(params[:id])
  	if story.present? && !story.staff_pick
  	  story.staff_pick = true
  	  story.save(:validate => false)
  	end

    respond_to do |format|
      format.json { render json: nil , status: :created }
    end
  end

  def staff_unpick
  	story = Story.is_published.find_by_permalink(params[:id])
  	if story.present? && story.staff_pick
  	  story.staff_pick = false
  	  story.save(:validate => false)
  	end

    respond_to do |format|
      format.json { render json: nil , status: :created }
    end
  end


  def like
    story = Story.is_published.find_by_permalink(params[:id])
    story.liked_by current_user if story.present?

    respond_to do |format|
      format.json { render json: nil , status: :created }
    end

  end


  def unlike
    story = Story.is_published.find_by_permalink(params[:id])
    story.unliked_by current_user if story.present?

    respond_to do |format|
      format.json { render json: nil , status: :created }
    end
  end

  def record_comment
    story = Story.is_published.find_by_permalink(params[:id])
    story.increment_comment_count if story.present?

    respond_to do |format|
      format.json { render json: {count: story.present? ? story.comments_count : 0} , status: :created }
    end
  end

end

app/views/storyteller/index.html.erb
<%
  @template = @story.template_id.present? ? @story.template_id : 1
  @export ||= false
  @no_nav ||= false
  @short_url = @story.shortened_url.present? ? @story.shortened_url : storyteller_show_url(@story.permalink)
  @section_count = 0
%>
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <%= render partial: "storyteller/template/#{@template}/head"%>
	  <%= include_gon if !@export %>
    <meta name="google" content="notranslate" />
  </head>
  <body>
    <% if !@export %>
      <%= render partial: "layouts/storybuilder_nav" if !@no_nav %>
    <% end %>
    <div id='storyTeller' lang="<%= @story.current_locale %>">
      <%= render partial: "storyteller/template/#{@template}/content"%>
    </div>
  <% if !@export %>
    <div class="info-bottom">
      <div class="info-row">
        <div class="l">
          <div class='authors'>
              <% @story.authors.each{|t| %>
                <div class='author js-u-dib'>
                  <div class='avatar'>
                    <%= link_to image_tag(t.avatar_url, :class=>"avatar"),  author_path(t.permalink), :class => "avatar", :"data-toggle"=>"dropdown" %>
                  </div>
                  <div class='name'>
                    <%= link_to t.name, author_path(t.permalink), :title => t.name %>
                  </div>
                  <div class="follow">
                    <%= render partial: 'layouts/follow_link', locals: {:locale => @story.current_locale, :user_id => t.id, :is_story_page => true, :page_to_return_to => storyteller_show_path(:id => @story.permalink, :process_follow => true)} %>
                  </div>
                </div>
              <% } %>
          </div>
        </div>

        <% if @section_count != 1 %>
          <div class="r">
              <div class='share'>
               <div class="addthis_native_toolbox"></div>
                <%= link_to '#',   :'data-modalos-id' => "modalos-embed", :title => t('app.common.embed', locale: @story.current_locale), :class => "embed modalEmbed" do %>
                <% end %>
                <% if @story.has_disclaimer %>
                <div class="disclaimer" data-tip="<%= t('storyteller.disclaimer_text') %>"><%= t('storyteller.disclaimer') %></div>
                <% end %>
              </div>
          </div>
        <% end %>
      </div>
      <div class="comments">
        <div class="fb-comments" data-href="<%= storyteller_show_url(:id=>@story.permalink,:sl => @story.current_locale) %>" data-num-posts="5" data-width="100%" id="fbComments"></div>
      </div>
      <% if !@stories.blank? %>
        <div class="related-links">
          <div class="h1"><%= t('storyteller.related_stories') %></div>
          <div class="themes">
            <span><%= t('storyteller.view_all_stories_in') %>&nbsp;</span>
            <% @story.themes.published.each { |t| %>
              <%= link_to t.name.split.map(&:capitalize).join(' '), theme_path(t.permalink) %>
            <% } %>
          </div>
        </div>
      <% end %>
    </div>


  <% if !@stories.blank? %>
    <div class="related-stories">
      <div class="grid-wrapper">
        <div class="grid col-4">
          <% @stories.each_with_index do |story,s_i| %>
            <% story.set_to_app_locale %>
            <div class="col n-3" lang="<%= story.current_locale %>">
              <%= render partial: "shared/grid_item" , locals:{:story=>story} %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
  <div class="footer story">
       <%= link_to(image_tag("svg/slogo.svg",:style=>"vertical-align:middle;",:alt=>t('app.common.app_name_not_trans')) , root_path(:locale => I18n.locale), title: t('app.common.app_name'), :class=>"slogo-bottom") %>
      <%= link_to(image_tag("svg/logo.svg",:style=>"vertical-align:middle;",:alt=>t('app.common.app_name_not_trans')) , root_path(:locale => I18n.locale), title: t('app.common.app_name'), :class=>"logo") %>
      <div class="powered-by">
        <%= t("app.common.powered_by") %>&nbsp;&nbsp;<a href="https://www.jumpstart.ge" target="_blank" title="<%= t("app.common.js_link_title") %>"><%= t("app.common.powered_by_js") %></a><%= t("app.common.powered_by_end") %>
      </div>
      <div class="center">
        <div><%= link_to t('helpers.links.about'), about_path %></div>
        <div>|</div>
        <div class='copy' data-tip="<%= t('layouts.application.copyright_text') %>">&copy; <%= t('layouts.application.copyright') %></div>
      </div>
  </div>

    <div id="modalos-embed" style="display:none;" class="embed-window">
      <div class="title"><%= "#{t('app.common.share_story')}" %></div>
      <div class="permalink"><%= "#{t('app.common.permalink')}" %>:</div>
      <div class="permalink-link"><%= link_to storyteller_show_url(@story.permalink), storyteller_show_url(@story.permalink) %></div>
      <div class="shortened-url"><%= "#{t('app.common.shortened_url')}" %>:</div>
      <div class="shortened-url-link"><%= link_to @story.shortened_url, @story.shortened_url if @story.shortened_url.present? %></div>

      <div class="embed">
        <div class="embed-icon"><i class="s i-embed"></i></div>
        <div class="embed-text"><%= "#{t('app.msgs.embed_code')}" %>:</div>
        <div class="embed-code">
        <textarea rows="6" cols="10"  data-iframe-link="<%=embed_url(@story.permalink) %>"
        readonly="" onfocus="setTimeout(function (t){ t.select(); }, 10, this);" onmouseup="return false;"><iframe src='<%=embed_url(@story.permalink) %>?type=partial' width='350' height='100%' frameborder='0'></iframe></textarea>
          <div class="embed-type-switcher">
            <div class="partial selected" title="<%= "#{t('app.common.partial_text')}" %>" data-width="350"><%= "#{t('app.common.partial')}" %></div>
            <div class="full" title="<%= "#{t('app.common.full_text')}" %>" data-width="1000"><%= "#{t('app.common.full')}" %></div>
            <div class="embed-size-w">
              <input type="text" value="350" class="iframe-size"/>
              <span>px <%= "#{t('app.common.wide')}" %></span>
            </div>
          </div>


        </div>
      </div>
    </div>
    <div class="tip" data-pointer="down"><div class="pointer up"></div><div class="content"></div><div class="pointer down"></div></div>
  <% end %>
      <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.4.4/d3.min.js" charset="utf-8"></script>
      <script>
/*********************************************************************************************
                                       data
**********************************************************************************************/
        var path =
        {
          <% if !@export %> // normal
            fullscreen:
            {
              desktop:
              {
                video: "/system/places/video/<%= @story.id %>/processed/",
                poster: "/system/places/video/<%= @story.id %>/poster/",
                image: "/system/places/images/<%= @story.id %>/fullscreen/",
                audio: "/system/places/audio/<%= @story.id %>/"
              },
              other:
              { image: "/system/places/images/<%= @story.id %>/mobile_1024/" }
            },
            slideshow:
            {
              desktop:{
                image: "/system/places/slideshow/<%= @story.id %>/slideshow/",
                thumb: "/system/places/slideshow/<%= @story.id %>/thumbnail/"
              },
              other: { image: "/system/places/slideshow/<%= @story.id %>/mobile_1024/"}
            }
          <% else %> // exported
            fullscreen:
            {
              desktop:
              {
                video: "media/video/processed/",
                poster: "media/video/poster/",
                image: "media/images/fullscreen/",
                audio: "media/audio/"
              },
              other:
              { image: "images/slideshow/mobile_1024/" }
            },
            slideshow:
            {
              desktop:{
                image: "media/slideshow/slideshow/",
                thumb: "media/slideshow/thumbnail/"
              },
              other: { image: "media/slideshow/mobile_1024/" }
            }
          <% end %>
        };

       <% if @story.sections.index{|t| t.youtube? && t.youtube.present? }.present? %>

         <%  youtube = []
              @story.sections.select{|t| t.ok? }.sort_by{|v| v.position}.each_with_index do |s,s_i|
                item = {}
                if s.youtube?
                  item[:type] = "youtube"
                  item[:videoId] = s.youtube.code
                  # item[:width] = 640
                  # item[:height] = 360
                  item[:loop] = s.youtube.loop ? 1 : 0
                  item[:info] = s.youtube.info ? 1 : 0
                  item[:cc_load_policy] = s.youtube.cc ? 1 : 0
                  item[:hl] = s.youtube.menu_lang
                  item[:cc_lang_pref] = s.youtube.cc_lang
                  item[:rel] = 0
                  youtube<< item
                end
              end
          %>
          var youtube = <%=youtube.to_json.html_safe %>;

          var tag = document.createElement('script');
          tag.src = "https://www.youtube.com/iframe_api";
          var firstScriptTag = document.getElementsByTagName('script')[0];
          firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);
          var youtubePlayers= [];
          function onYouTubePlayerAPIReady() {
            var youtubeContainers = d3.selectAll(".section .container div[data-yid]");

            if(youtubeContainers[0].length == youtube.length)
            {
              youtube.forEach(function(d,i){
                  if(d.videoId == youtubeContainers[0][i].dataset.yid)
                  {
                    youtubePlayers.push(new YT.Player(
                        youtubeContainers[0][i],
                        {
                          videoId: d.videoId,
                          // width: "100%",
                          // height: "100%",
                          // width: d.width,
                          // height: d.height,
                          playerVars:{
                            showinfo: d.info,
                            loop: d.loop,
                            cc_load_policy: d.cc_load_policy,
                            hl: d.hl,
                            cc_lang_pref: d.cc_lang_pref,
                            rel: d.rel
                          },
                          events: { 'onStateChange': onPlayerStateChange }
                        }
                    ));
                  }
              });
              console.log(youtubePlayers);
            }
          }
          function onPlayerStateChange(event) {
            if (event.data == 1){
              if (event.target.hasAlreadyPlayed == undefined){
                var locale = event.target.d.d.playerVars.cc_lang_pref;
                var load_policy = event.target.d.d.playerVars.cc_load_policy;
                if (locale != undefined && load_policy == 1){
                  event.target.loadModule("captions");  //Works for html5 ignored by AS3
                  event.target.setOption("captions", "track", {"languageCode": locale});  //Works for html5 ignored by AS3
                  event.target.loadModule("cc");  //Works for AS3 ignored by html5
                  event.target.setOption("cc", "track", {"languageCode": locale});  //Works for AS3 ignored by html5
                }
                event.target.hasAlreadyPlayed = true;
              }
            }
          }
        <% end %>
      </script>


    <% if !@export %>
      <%= javascript_include_tag  *(@js.present? ? ["application", "story", @js].flatten : ["application", "story"]), :media => "all" %>
    <% else %>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
      <script src="js/bootstrap.min.js"></script>
      <script src="js/modalos.js"></script>
      <script src="js/story.js"></script>
      <script src="js/page.js"></script>
    <% end %>

    <% if !@export %>
      <div id="fb-root"></div>
      <script>
        I18n.defaultLocale = "<%= I18n.default_locale %>";
        I18n.locale = "<%= I18n.locale %>";

        (function(d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return;
          js = d.createElement(s); js.id = id;
          js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=<%= @face_id %>&version=v2.0";
          fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));

        <% if Rails.env.production? %>
          (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
          })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
          ga('create', 'UA-12801815-39', 'auto');
          ga('send', 'pageview');
        <% end %>

        <%
          addthis_id = Rails.env.production? ? ENV['STORY_BUILDER_ADDTHIS_PROFILEID'] : 'ra-51d1537d4a09d85f'
          if addthis_id.present?
        %>
          var addthis_share = { url: '<%= @short_url %>' }
        <% end %>
      </script>
      <% if addthis_id.present? %>
        <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=<%= addthis_id %>" async="async"></script>
      <% end %>
    <% end %>

  </body>
</html>